export const SAY_HELLO = 'SAY_HELLO';
export const SAY_HELLO_ASYNC_START = 'SAY_HELLO_ASYNC_START';
export const SAY_HELLO_ASYNC_DONE = 'SAY_HELLO_ASYNC_DONE';
export const SAY_HELLO_ASYNC_ERROR = 'SAY_HELLO_ASYNC_ERROR';
